//
//  Constants.swift
//  Streaks
//
//  Created by Vaed Prasad on 7/31/18.
//  Copyright © 2018 Vaed Prasad. All rights reserved.
//

import Foundation

struct Constants {
    struct Segue {
        static let toChallengeDetailFromHome = "toChallengeDetailFromHome"
        static let toChallengeDetailFromKoloda = "toChallengeDetailFromKoloda"
        static let toNewChallengeDetail = "toNewChallengeDetail"
        static let toCreateChallenge = "toCreateChallenge"
        static let saveChallenge = "saveChallenge"
        static let saveNewChallenge = "saveNewChallenge"
        static let toIconSelector = "toIconSelector"
        static let backToNewChallengeDetail = "backToNewChallengeDetail"
    }
    
    struct UserDefaults {
        static let currentUser = "currentUser"
    }
    
    struct ListNewChallenges {
        struct NewChallenges {
            var sectionName: String
            var isCustom = Bool()
            var sectionChallenges: [Challenge]
        }
        static let user = CurrentUser.current
        static let newChallenges = [
            NewChallenges(sectionName: "Custom Challenge", isCustom: true, sectionChallenges: [Challenge(name: "Custom Challenge", icon: "pencil", creator: user)]),
            NewChallenges(sectionName: "Preset Challenges", isCustom: false, sectionChallenges: [
                Challenge(name: "Eat a Healthy Meal", icon: "broccoli", creator: user),
                Challenge(name: "Workout", icon: "seated_dumbbell", creator: user),
                Challenge(name: "No Alcohol", icon: "no_alcohol", creator: user),
                Challenge(name: "No Smoking", icon: "no_smoking", creator: user),
                Challenge(name: "No Facebook", icon: "facebook", creator: user),
                Challenge(name: "Walk Dog", icon: "dog", creator: user),
                Challenge(name: "Practice Piano", icon: "piano", creator: user),
                Challenge(name: "Be Vegetarian", icon: "vegetarian", creator: user)

                ])
        ]
    }
    struct Icons {
        static let newChallengeIcons = [
            Icon(iconName: "Abs", iconImageIdentifier: "abs"),
            Icon(iconName: "Accounting", iconImageIdentifier: "accounting"),
            Icon(iconName: "Acrobatics", iconImageIdentifier: "acrobatics"),
            Icon(iconName: "Airplane", iconImageIdentifier: "airplane"),
            Icon(iconName: "Alpine Skiing", iconImageIdentifier: "alpine_skiing"),
            Icon(iconName: "Apple", iconImageIdentifier: "apple"),
            Icon(iconName: "Apricot", iconImageIdentifier: "apricot"),
            Icon(iconName: "Archery", iconImageIdentifier: "archery"),
            Icon(iconName: "Asparagus", iconImageIdentifier: "asparagus"),
            Icon(iconName: "Avocado", iconImageIdentifier: "avocado"),
            Icon(iconName: "Baby", iconImageIdentifier: "baby"),
            Icon(iconName: "Back Muscles", iconImageIdentifier: "back_muscles"),
            Icon(iconName: "Bacon", iconImageIdentifier: "bacon"),
            Icon(iconName: "Badminton", iconImageIdentifier: "badminton"),
            Icon(iconName: "Baguette", iconImageIdentifier: "baguette"),
            Icon(iconName: "Banana", iconImageIdentifier: "banana"),
            Icon(iconName: "Beet", iconImageIdentifier: "beet"),
            Icon(iconName: "Bell", iconImageIdentifier: "bell"),
            Icon(iconName: "Bench Press", iconImageIdentifier: "bench_press"),
            Icon(iconName: "Bento Box", iconImageIdentifier: "bento"),
            Icon(iconName: "Berry", iconImageIdentifier: "berry"),
            Icon(iconName: "Biceps", iconImageIdentifier: "biceps"),
            Icon(iconName: "Books", iconImageIdentifier: "books"),
            Icon(iconName: "Bowling", iconImageIdentifier: "bowling"),
            Icon(iconName: "Boxing", iconImageIdentifier: "boxing"),
            Icon(iconName: "Bread", iconImageIdentifier: "bread"),
            Icon(iconName: "Broccoli", iconImageIdentifier: "broccoli"),
            Icon(iconName: "Bungee", iconImageIdentifier: "bungee_jumping"),
            Icon(iconName: "Bus", iconImageIdentifier: "bus"),
            Icon(iconName: "Cabbage", iconImageIdentifier: "cabbage"),
            Icon(iconName: "Cake", iconImageIdentifier: "cake"),
            Icon(iconName: "Calculator", iconImageIdentifier: "calculator"),
            Icon(iconName: "Calendar", iconImageIdentifier: "calendar"),
            Icon(iconName: "Calories", iconImageIdentifier: "caloric_energy"),
            Icon(iconName: "Calves", iconImageIdentifier: "calves"),
            Icon(iconName: "Camera", iconImageIdentifier: "camera"),
            Icon(iconName: "Campfire", iconImageIdentifier: "campfire"),
            Icon(iconName: "Car", iconImageIdentifier: "car"),
            Icon(iconName: "Carbohydrates", iconImageIdentifier: "carbohydrates"),
            Icon(iconName: "Carrot", iconImageIdentifier: "carrot"),
            Icon(iconName: "Cauliflower", iconImageIdentifier: "cauliflower"),
            Icon(iconName: "Celery", iconImageIdentifier: "celery"),
            Icon(iconName: "Cheese", iconImageIdentifier: "cheese"),
            Icon(iconName: "Cherry", iconImageIdentifier: "cherry"),
            Icon(iconName: "Chest", iconImageIdentifier: "chest"),
            Icon(iconName: "Chili Pepper", iconImageIdentifier: "chili_pepper"),
            Icon(iconName: "Chocolate", iconImageIdentifier: "chocolate"),
            Icon(iconName: "Cinnamon Roll", iconImageIdentifier: "cinnamon_roll"),
            Icon(iconName: "Citrus", iconImageIdentifier: "citrus"),
            Icon(iconName: "Classroom", iconImageIdentifier: "classroom"),
            Icon(iconName: "Climbing", iconImageIdentifier: "climbing"),
            Icon(iconName: "Coconut", iconImageIdentifier: "coconut"),
            Icon(iconName: "Compass", iconImageIdentifier: "compass"),
            Icon(iconName: "Compost", iconImageIdentifier: "compost"),
            Icon(iconName: "Cookies", iconImageIdentifier: "cookies"),
            Icon(iconName: "Corn", iconImageIdentifier: "corn"),
            Icon(iconName: "Cotton Candy", iconImageIdentifier: "cotton_candy"),
            Icon(iconName: "Crab", iconImageIdentifier: "crab"),
            Icon(iconName: "Croissant", iconImageIdentifier: "croissant"),
            Icon(iconName: "Cruise Ship", iconImageIdentifier: "cruise_ship"),
            Icon(iconName: "Cucumber", iconImageIdentifier: "cucumber"),
            Icon(iconName: "Cupcake", iconImageIdentifier: "cupcake"),
            Icon(iconName: "Curling", iconImageIdentifier: "curling"),
            Icon(iconName: "Dancing", iconImageIdentifier: "dancing"),
            Icon(iconName: "Dim Sum", iconImageIdentifier: "dim_sum"),
            Icon(iconName: "Dog", iconImageIdentifier: "dog"),
            Icon(iconName: "Doughnut", iconImageIdentifier: "doughnut"),
            Icon(iconName: "Dragon Fruit", iconImageIdentifier: "dragon_fruit"),
            Icon(iconName: "Dumbbell", iconImageIdentifier: "dumbbell"),
            Icon(iconName: "Dumbbell Curl", iconImageIdentifier: "dumbbell_curl"),
            Icon(iconName: "Dggplant", iconImageIdentifier: "eggplant"),
            Icon(iconName: "Exercise", iconImageIdentifier: "exercise"),
            Icon(iconName: "Facebook", iconImageIdentifier: "facebook"),
            Icon(iconName: "Family", iconImageIdentifier: "family"),
            Icon(iconName: "Fencing", iconImageIdentifier: "fencing"),
            Icon(iconName: "Finish Flag", iconImageIdentifier: "finish_flag"),
            Icon(iconName: "Fish", iconImageIdentifier: "fish"),
            Icon(iconName: "Fishing Pole", iconImageIdentifier: "fishing_pole"),
            Icon(iconName: "Food Wine", iconImageIdentifier: "food_wine"),
            Icon(iconName: "French Fries", iconImageIdentifier: "french_fries"),
            Icon(iconName: "Frisbee", iconImageIdentifier: "frisbee"),
            Icon(iconName: "Garlic", iconImageIdentifier: "garlic"),
            Icon(iconName: "Glutes", iconImageIdentifier: "glutes"),
            Icon(iconName: "Golf", iconImageIdentifier: "golf"),
            Icon(iconName: "Graduation Cap", iconImageIdentifier: "graduation_cap"),
            Icon(iconName: "Grapes", iconImageIdentifier: "grapes"),
            Icon(iconName: "Grocery Bag", iconImageIdentifier: "grocery_bag"),
            Icon(iconName: "Guitar", iconImageIdentifier: "guitar"),
            Icon(iconName: "Hamburger", iconImageIdentifier: "hamburger"),
            Icon(iconName: "Hamstrings", iconImageIdentifier: "hamstrings"),
            Icon(iconName: "Hazelnut", iconImageIdentifier: "hazelnut"),
            Icon(iconName: "High Importance", iconImageIdentifier: "high_importance"),
            Icon(iconName: "Horseback Riding", iconImageIdentifier: "horseback_riding"),
            Icon(iconName: "Hot Dog", iconImageIdentifier: "hot_dog"),
            Icon(iconName: "Ice Cream", iconImageIdentifier: "ice_cream"),
            Icon(iconName: "Ingredients", iconImageIdentifier: "ingredients"),
            Icon(iconName: "Instagram", iconImageIdentifier: "instagram"),
            Icon(iconName: "Jump Rope", iconImageIdentifier: "jump_rope"),
            Icon(iconName: "Kebab", iconImageIdentifier: "kebab"),
            Icon(iconName: "Kiwi", iconImageIdentifier: "kiwi"),
            Icon(iconName: "Lamb", iconImageIdentifier: "lamb"),
            Icon(iconName: "Leek", iconImageIdentifier: "leek"),
            Icon(iconName: "Lettuce", iconImageIdentifier: "lettuce"),
            Icon(iconName: "Luge", iconImageIdentifier: "luge"),
            Icon(iconName: "Meditate", iconImageIdentifier: "meditate"),
            Icon(iconName: "Melon", iconImageIdentifier: "melon"),
            Icon(iconName: "Mushroom", iconImageIdentifier: "mushroom"),
            Icon(iconName: "Nachos", iconImageIdentifier: "nachos"),
            Icon(iconName: "Neck", iconImageIdentifier: "neck"),
            Icon(iconName: "No Alcohol", iconImageIdentifier: "no_alcohol"),
            Icon(iconName: "No Apple", iconImageIdentifier: "no_apple"),
            Icon(iconName: "No Celery", iconImageIdentifier: "no_celery"),
            Icon(iconName: "No Crustaceans", iconImageIdentifier: "no_crustaceans"),
            Icon(iconName: "No Eggs", iconImageIdentifier: "no_eggs"),
            Icon(iconName: "No Fish", iconImageIdentifier: "no_fish"),
            Icon(iconName: "No Fructose", iconImageIdentifier: "no_fructose"),
            Icon(iconName: "No Gluten", iconImageIdentifier: "no_gluten"),
            Icon(iconName: "No Gmo", iconImageIdentifier: "no_gmo"),
            Icon(iconName: "No Milk", iconImageIdentifier: "no_milk"),
            Icon(iconName: "No Mustard", iconImageIdentifier: "no_mustard"),
            Icon(iconName: "No Nuts", iconImageIdentifier: "no_nuts"),
            Icon(iconName: "No Peanut", iconImageIdentifier: "no_peanut"),
            Icon(iconName: "No Salt", iconImageIdentifier: "no_salt"),
            Icon(iconName: "No Sesame", iconImageIdentifier: "no_sesame"),
            Icon(iconName: "No Shellfish", iconImageIdentifier: "no_shellfish"),
            Icon(iconName: "No Smoking", iconImageIdentifier: "no_smoking"),
            Icon(iconName: "No Soy", iconImageIdentifier: "no_soy"),
            Icon(iconName: "No Sugar", iconImageIdentifier: "no_sugar"),
            Icon(iconName: "Non Vegetarian", iconImageIdentifier: "non_vegetarian"),
            Icon(iconName: "Noodles", iconImageIdentifier: "noodles"),
            Icon(iconName: "Nut", iconImageIdentifier: "nut"),
            Icon(iconName: "Octopus", iconImageIdentifier: "octopus"),
            Icon(iconName: "Olive Oil", iconImageIdentifier: "olive_oil"),
            Icon(iconName: "Olive", iconImageIdentifier: "olive"),
            Icon(iconName: "Onion", iconImageIdentifier: "onion"),
            Icon(iconName: "Orange", iconImageIdentifier: "orange"),
            Icon(iconName: "Paddling", iconImageIdentifier: "paddling"),
            Icon(iconName: "Paella", iconImageIdentifier: "paella"),
            Icon(iconName: "Pancake", iconImageIdentifier: "pancake"),
            Icon(iconName: "Papaya", iconImageIdentifier: "papaya"),
            Icon(iconName: "Paprika", iconImageIdentifier: "paprika"),
            Icon(iconName: "Parkour", iconImageIdentifier: "parkour"),
            Icon(iconName: "Pasta", iconImageIdentifier: "pasta"),
            Icon(iconName: "Peach", iconImageIdentifier: "peach"),
            Icon(iconName: "Peanuts", iconImageIdentifier: "peanuts"),
            Icon(iconName: "Pear", iconImageIdentifier: "pear"),
            Icon(iconName: "Peas", iconImageIdentifier: "peas"),
            Icon(iconName: "Phone", iconImageIdentifier: "phone"),
            Icon(iconName: "Piano", iconImageIdentifier: "piano"),
            Icon(iconName: "Pineapple", iconImageIdentifier: "pineapple"),
            Icon(iconName: "Ping Pong", iconImageIdentifier: "ping_pong"),
            Icon(iconName: "Pizza", iconImageIdentifier: "pizza"),
            Icon(iconName: "Plum", iconImageIdentifier: "plum"),
            Icon(iconName: "Pomegranate", iconImageIdentifier: "pomegranate"),
            Icon(iconName: "Potato", iconImageIdentifier: "potato"),
            Icon(iconName: "Prawn", iconImageIdentifier: "prawn"),
            Icon(iconName: "Pretzel", iconImageIdentifier: "pretzel"),
            Icon(iconName: "Pullups", iconImageIdentifier: "pullups"),
            Icon(iconName: "Pushups", iconImageIdentifier: "pushups"),
            Icon(iconName: "Racquetball", iconImageIdentifier: "racquetball"),
            Icon(iconName: "Radish", iconImageIdentifier: "radish"),
            Icon(iconName: "Raspberry", iconImageIdentifier: "raspberry"),
            Icon(iconName: "Rice", iconImageIdentifier: "rice"),
            Icon(iconName: "Rowing", iconImageIdentifier: "rowing"),
            Icon(iconName: "Rugby", iconImageIdentifier: "rugby"),
            Icon(iconName: "Sail Boat", iconImageIdentifier: "sail_boat"),
            Icon(iconName: "Salami", iconImageIdentifier: "salami"),
            Icon(iconName: "Sauce", iconImageIdentifier: "sauce"),
            Icon(iconName: "Sausages", iconImageIdentifier: "sausages"),
            Icon(iconName: "Seated Dumbbell", iconImageIdentifier: "seated_dumbbell"),
            Icon(iconName: "Security", iconImageIdentifier: "security"),
            Icon(iconName: "Shellfish", iconImageIdentifier: "shellfish"),
            Icon(iconName: "Shooting", iconImageIdentifier: "shooting"),
            Icon(iconName: "Shopping Cart", iconImageIdentifier: "shopping_cart"),
            Icon(iconName: "Shoulders", iconImageIdentifier: "shoulders"),
            Icon(iconName: "Sit Ups", iconImageIdentifier: "sit_ups"),
            Icon(iconName: "Skateboard", iconImageIdentifier: "skateboard"),
            Icon(iconName: "Skiing", iconImageIdentifier: "skiing"),
            Icon(iconName: "Sleeping Bag", iconImageIdentifier: "sleeping_bag"),
            Icon(iconName: "Soccer", iconImageIdentifier: "soccer"),
            Icon(iconName: "Sodium", iconImageIdentifier: "sodium"),
            Icon(iconName: "Soy", iconImageIdentifier: "soy"),
            Icon(iconName: "Squats", iconImageIdentifier: "squats"),
            Icon(iconName: "Stairs", iconImageIdentifier: "stairs"),
            Icon(iconName: "Steak", iconImageIdentifier: "steak"),
            Icon(iconName: "Students", iconImageIdentifier: "students"),
            Icon(iconName: "Sugar", iconImageIdentifier: "sugar"),
            Icon(iconName: "Survival Bag", iconImageIdentifier: "survival_bag"),
            Icon(iconName: "Sushi", iconImageIdentifier: "sushi"),
            Icon(iconName: "Sweet Potato", iconImageIdentifier: "sweet_potato"),
            Icon(iconName: "Swimming", iconImageIdentifier: "swimming"),
            Icon(iconName: "Table Tennis", iconImageIdentifier: "table_tennis"),
            Icon(iconName: "Taco", iconImageIdentifier: "taco"),
            Icon(iconName: "Taxi", iconImageIdentifier: "taxi"),
            Icon(iconName: "Tennis Ball", iconImageIdentifier: "tennis_ball"),
            Icon(iconName: "Tennis Racquet", iconImageIdentifier: "tennis_racquet"),
            Icon(iconName: "Tennis", iconImageIdentifier: "tennis"),
            Icon(iconName: "Tent", iconImageIdentifier: "tent"),
            Icon(iconName: "Thanksgiving", iconImageIdentifier: "thanksgiving"),
            Icon(iconName: "Tomato", iconImageIdentifier: "tomato"),
            Icon(iconName: "Treadmill", iconImageIdentifier: "treadmill"),
            Icon(iconName: "Trekking", iconImageIdentifier: "trekking"),
            Icon(iconName: "Triceps", iconImageIdentifier: "triceps"),
            Icon(iconName: "Vegan", iconImageIdentifier: "vegan"),
            Icon(iconName: "Vegetarian Food", iconImageIdentifier: "vegetarian_food"),
            Icon(iconName: "Vegetarian", iconImageIdentifier: "vegetarian"),
            Icon(iconName: "Video Games", iconImageIdentifier: "video_games"),
            Icon(iconName: "Walking", iconImageIdentifier: "walking"),
            Icon(iconName: "Water Polo", iconImageIdentifier: "water_polo"),
            Icon(iconName: "Watermelon", iconImageIdentifier: "watermelon"),
            Icon(iconName: "Weightlift", iconImageIdentifier: "weightlift"),
            Icon(iconName: "Wheelchair", iconImageIdentifier: "wheelchair"),
            Icon(iconName: "Wrap", iconImageIdentifier: "wrap"),
            Icon(iconName: "Wrestling", iconImageIdentifier: "wrestling"),
            Icon(iconName: "Yoga", iconImageIdentifier: "yoga"),
            Icon(iconName: "Youtube", iconImageIdentifier: "youtube"),
            Icon(iconName: "Zucchini", iconImageIdentifier: "zucchini")
        ]
    }
    
}
